import type { Metadata } from "next";
import { Inter, Poppins, Rubik_Mono_One } from "next/font/google";
import "./globals.css";

const rubik_mono_one = Rubik_Mono_One({
  weight: ["400"],
  variable: "--font-display",
  subsets: ["latin"],
});
const inter = Inter({
  weight: ["400", "500", "600", "700"],
  variable: "--font-body",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  variable: "--font-headings",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik_mono_one.variable} ${inter.variable} ${poppins.variable} font-body`}
      >
        {children}
      </body>
    </html>
  );
}
